# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).
  
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    env: 'infrastructure' # C'est simplement le nom de votre environnement

# spécification du serveur alertmanager
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
    scheme: http
    timeout: 10s

# fichier de règles pour l'alerting, c'est dans ce fichier que sont les définitions des alertes
rule_files:
- '/alertmanager/alert.rules/alerts.rules.yml'

scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 5s
  static_configs:
    - targets: ['prometheus:9090']

- job_name: 'node-exporter'
  scrape_interval: 5s
  static_configs:
  - targets: ['node-exporter:9100']

#- job_name: 'pushgateway'
#  scrape_interval: 10s
#   static_configs:
#     - targets: ['pushgateway:9091']

- job_name: 'postgres-exporter'
  scrape_interval: 300s
  scrape_timeout: 60s
  static_configs:
  - targets: ['postgres-exporter:9187']

- job_name: 'rabbitmq'
  metrics_path: /metrics/per-object
  static_configs:
  - targets: ['rabbitmq:15692']

- job_name: 'redis-exporter'
  static_configs:
  - targets: ['redis-exporter:9121']

- job_name: 'flower'
  static_configs:
  - targets: ['flower:5555']

- job_name: 'project-api'
  static_configs:
  - targets: ['project-api:5000']
